[package]
name = "advent_of_code_2022"
version = "0.0.1"
authors = ["Jeff Paril <jeffersonparil@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
